when:
  - event: push
    branch: main

steps:
  - name: Build plugin
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ghcr.io
      - docker build -t ghcr.io/bigaston/discordnotification:latest discordnotification
      - docker push ghcr.io/bigaston/discordnotification:latest

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD