when:
  - event: push
    branch: main

steps:
  - name: Build plugin
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ghcr.io
      - docker build -t ghcr.io/bigaston/discordnotification:latest discordnotification
      - docker push ghcr.io/bigaston/discordnotification:latest
      
      # Codeberg
      - docker login -u $DOCKER_CODEBERG_USERNAME -p $DOCKER_CODEBERG_PASSWORD codeberg.org
      - docker image tag ghcr.io/bigaston/discordnotification:latest codeberg.org/bigaston/discordnotification:latest
      - docker push codeberg.org/bigaston/discordnotification:latest

      - docker builder prune --filter until=24h --force
      - docker image prune --filter until=24h --force

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_CODEBERG_USERNAME:
        from_secret: DOCKER_CODEBERG_USERNAME
      DOCKER_CODEBERG_PASSWORD:
        from_secret: DOCKER_CODEBERG_PASSWORD